spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://localhost:3306/client_a
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        wrapperClientDriver: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
      jdbc:
        lob:
          non_contextual_creation: true
  sql:
    init:
      mode: never


aws:
  region: 
  access-key: 
  secret-key: 


cognito:
  issuers: 
  user-pool-id: 
  client-id: 

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 8080

spring-doc:
  override-with-generic-response: false
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.aws.cognito.poc.controller

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: always
